//THIS FILE IS GENERATED
#define CRTMPSERVER_VERSION_BUILD_DATE 1397804230
#define CRTMPSERVER_VERSION_BUILD_NUMBER "已导出 "
#define CRTMPSERVER_VERSION_RELEASE_NUMBER "1.1_rc1"
#define CRTMPSERVER_VERSION_CODE_NAME "Gladiator"
#define CRTMPSERVER_VERSION_BUILDER_OS_NAME ""
#define CRTMPSERVER_VERSION_BUILDER_OS_VERSION ""
#define CRTMPSERVER_VERSION_BUILDER_OS_ARCH ""
#define CRTMPSERVER_VERSION_BUILDER_OS_UNAME "Linux localhost.localdomain 2.6.32-71.el6.x86_64 #1 SMP Fri May 20 03:51:51 BST 2011 x86_64 x86_64 x86_64 GNU/Linux"
